# Generated by Django 4.1.1 on 2022-12-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_city_options_alter_city_name_alter_city_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
